<?//d($flat_data);?>
<table id="box-table-a" class="tablesorter" summary="Stats">
<thead>
    <tr>
    	<th>Group</th>
        <th>Function</th>
        <th>Call Count</th>
        <th>Wall Time</th>
        <th>CPU</th>
        <th>Memory Usage</th>
        <th>Peak Memory Usage</th>
        <th>Exclusive Wall Time</th>
        <th>Exclusive CPU</th>
        <th>Exclusive Memory Usage</th>
        <th>Exclusive Peak Memory Usage</th>
    </tr>
</thead>
<tbody>
    <?foreach($flat_data as $element):?>
        <?
            if (isset($element['group'])) {
                $color = $function_color[$element['group']];
            } elseif (isset($function_color[$element['fn']])) {
                $color = $function_color[$element['fn']];
            } else {
              $color = 'inherit';
            }
        ?>
    
    <tr>

	    <td style="background-color: <?=$color?>;"><span style="display: none"><?=$color?></span>&nbsp;</td>

        <td><a href="index.php?run=<?=$run1?>&amp;symbol=<?=urlencode($element['fn'])?>"><?= htmlentities($element['fn'], ENT_QUOTES, 'UTF-8')?></a></td>
        <td><?=(!empty($element['ct'])) ? $element['ct'] : ''?></td>
        <td><?=(!empty($element['wt'])) ? printTimeFormatSeconds($element['wt']) : ''?></td>
        <td><?=(!empty($element['cpu'])) ? printTimeFormatSeconds($element['cpu']) : ''?></td>
        <td><?=(!empty($element['mu'])) ? printMemoryFormatMb($element['mu']) : ''?></td>
        <td><?=(!empty($element['pmu'])) ? printMemoryFormatMb($element['pmu']) : ''?></td>
        <td><?=(!empty($element['excl_wt'])) ? printTimeFormatSeconds($element['excl_wt']) : ''?></td>
        <td><?=(!empty($element['excl_cpu'])) ? printTimeFormatSeconds($element['excl_cpu']) : ''?></td>
        <td><?=(!empty($element['excl_mu'])) ? printMemoryFormatMb($element['excl_mu']) : ''?></td>
        <td><?=(!empty($element['excl_pmu'])) ? printMemoryFormatMb($element['excl_pmu']) : ''?></td>
    </tr>

    <?endforeach;?>
</tbody>
</table>
<script type="text/javascript">
$(document).ready(function() 
    {
        $("#box-table-a").stickyTableHeaders();
        $("#box-table-a").tablesorter( {sortList: []} ); 
    } 
);
</script>
